"""
Django settings for ticket project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
dotenv.load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-w!6pye!qhw01mevr77v1(5cmwobbtn#pit9+xl0+0k-4np7z3+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't', 'y', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.getenv(
    'ALLOWED_HOSTS',
    '127.0.0.1,localhost,metrolinkssolutionltd.co.ke,tickets.metrolinkssolutionltd.co.ke,'
    '.ngrok-free.dev,.ngrok-free.app',
).split(',') if h.strip()]

# Required for HTTPS tunnels (e.g. ngrok) when submitting forms from a phone/browser.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'https://*.ngrok-free.dev,https://*.ngrok-free.app',
).split(',') if o.strip()]

# In DEBUG, always permit ngrok subdomains (tunnel URL changes each session).
if DEBUG:
    for _ngrok_host in ('.ngrok-free.dev', '.ngrok-free.app', '.ngrok.io'):
        if _ngrok_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_ngrok_host)
    for _ngrok_origin in ('https://*.ngrok-free.dev', 'https://*.ngrok-free.app'):
        if _ngrok_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_ngrok_origin)

# Absolute URL for the tickets portal login (landing page "Client Portal" link).
# Leave unset in development — links use the current host (e.g. http://127.0.0.1:8000/login/).
TICKETS_PORTAL_LOGIN_URL = os.getenv('TICKETS_PORTAL_LOGIN_URL', '').strip()
if not TICKETS_PORTAL_LOGIN_URL and not DEBUG:
    TICKETS_PORTAL_LOGIN_URL = 'https://tickets.metrolinkssolutionltd.co.ke/portal/login/'

# Base URL for ticket links in SMS when no HTTP request (e.g. webhooks). Unset = current host in views, production default when DEBUG=False.
SITE_BASE_URL = os.getenv('SITE_BASE_URL', '').strip()
if not SITE_BASE_URL and not DEBUG:
    SITE_BASE_URL = 'https://tickets.metrolinkssolutionltd.co.ke'

# Max options returned in hybrid search dropdowns (customers, agents, etc.)
HYBRID_SEARCH_RESULT_LIMIT = int(os.getenv('HYBRID_SEARCH_RESULT_LIMIT', '20'))

# --- AI Assistant (web + WhatsApp) ---
# OpenAI performs all intent understanding and tool selection (tool_choice=auto).
# Django only executes tools returned in the API response.
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '').strip()
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini').strip()
OPENAI_BASE_URL = os.getenv('OPENAI_BASE_URL', 'https://api.openai.com/v1').strip()
ASSISTANT_MAX_HISTORY = int(os.getenv('ASSISTANT_MAX_HISTORY', '24'))

# WhatsApp Cloud API (Meta Business)
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '').strip()
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '').strip()
WHATSAPP_VERIFY_TOKEN = os.getenv('WHATSAPP_VERIFY_TOKEN', '').strip()
WHATSAPP_API_VERSION = os.getenv('WHATSAPP_API_VERSION', 'v21.0').strip()
# Display number for wa.me link (digits only, e.g. 254792929275); defaults to primary office line
WHATSAPP_DISPLAY_NUMBER = os.getenv('WHATSAPP_DISPLAY_NUMBER', '').strip()

# Company contact (footer, landing, WhatsApp FAB)
COMPANY_PHONE_PRIMARY = os.getenv('COMPANY_PHONE_PRIMARY', '0792929275').strip()
COMPANY_PHONE_SECONDARY = os.getenv('COMPANY_PHONE_SECONDARY', '0746464696').strip()
COMPANY_EMAIL = os.getenv('COMPANY_EMAIL', 'metrolinkssolutionltd@gmail.com').strip()

# UjumbeSMS — ticket-created notifications (https://ujumbesms.co.ke)
UJUMBE_SMS_API_KEY = os.getenv('UJUMBE_SMS_API_KEY', '').strip()
UJUMBE_SMS_EMAIL = os.getenv('UJUMBE_SMS_EMAIL', '').strip()
UJUMBE_SMS_SENDER_ID = os.getenv('UJUMBE_SMS_SENDER_ID', 'UjumbeSMS').strip()
UJUMBE_SMS_BASE_URL = os.getenv('UJUMBE_SMS_BASE_URL', 'https://ujumbesms.co.ke').strip()
UJUMBE_SMS_ENABLED = os.getenv('UJUMBE_SMS_ENABLED', 'True').lower() in (
    'true', '1', 't', 'y', 'yes',
)
# Print [TKT-SMS] lines to the runserver terminal (defaults on when DEBUG=True)
SMS_DEBUG_PRINT = os.getenv('SMS_DEBUG_PRINT', str(DEBUG)).lower() in (
    'true', '1', 't', 'y', 'yes',
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_hosts',
    'core',
]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]

ROOT_URLCONF = 'ticket.urls'
ROOT_HOSTCONF = 'ticket.hosts'
# Bare host (127.0.0.1 / localhost) uses this named pattern. In dev, 'default' includes /login/.
DEFAULT_HOST = 'default' if DEBUG else 'www'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.portal_urls',
                'core.context_processors.portal_customer',
                'core.context_processors.staff_permissions',
                'core.context_processors.company_contact',
            ],
        },
    },
]

WSGI_APPLICATION = 'ticket.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite3')

if DB_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }
elif DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# When DEBUG=False, run collectstatic before deploy. If staticfiles/ is missing (local
# testing), WhiteNoise can serve from app folders via finders.
_whitenoise_use_finders = os.getenv('WHITENOISE_USE_FINDERS', '').strip()
if _whitenoise_use_finders:
    WHITENOISE_USE_FINDERS = _whitenoise_use_finders.lower() in ('true', '1', 't', 'y', 'yes')
else:
    WHITENOISE_USE_FINDERS = DEBUG or not (STATIC_ROOT / 'core').exists()

# WhiteNoise storage configuration for compression and caching
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

AUTH_USER_MODEL = 'core.MyUser'

AUTHENTICATION_BACKENDS = [
    'core.auth_backends.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Production Security Settings (Enabled when DEBUG is False or controlled by environment)
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 't', 'y', 'yes')
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False').lower() in ('true', '1', 't', 'y', 'yes')
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 't', 'y', 'yes')
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
